server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(aGTlDy1reUnCpcO6X8BFZlQgadu6YcO8/MCurlbIDLyCIf5kno/yvziDf5ybWCiidkmmYlqCPpteTCFl6KWnG9IW/FkfsUaI1hMiZIxOLA5tybQMbf+gelzIjaqNzBxjFfTgft+v0YKlTKz/IssdVA==)
    username: ENC(Z4l6hSIyC1IIgskkSctbjg==)
    password: ENC(/XfpxW7CMqcK3Ydp2+yALh8IUUDJcd2N)
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      #      ddl-auto: none
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator